name: Build OCI Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v7
    
    - name: Build Image
      run: |
        docker build -t prometheus-random-example:0728 .
    
    - name: Save image
      run: |
        docker save prometheus-random-example:0728 -o prometheus-random-example.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: oci-image
        path: prometheus-random-example.tar
